AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Coffee Project API
Resources:
  Get:
    Type: AWS::Serverless::Function
    Properties:
      Handler: coffee-project::coffee_project.Functions::Get
      Runtime: dotnetcore2.1
      CodeUri: ''
      MemorySize: 256
      Timeout: 30
      Role: 
      Policies:
      - AWSLambdaBasicExecutionRole
      Events:
        PutResource:
          Type: Api
          Properties:
            Path: "/"
            Method: GET
Outputs:
  ApiURL:
    Description: API endpoint URL for Prod environment
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
